version: '3.4'
services:
  web:
    build: docker/site
    ports:
      - 7575:80
    volumes:
      - ./www:/var/www/html/
      - ./docker/server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/server/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/server/php.ini:/usr/local/etc/php/php.ini